export const FEATCH_PHONES_START = 'FEATCH_PHONES_START'
export const FEATCH_PHONES_SUCCESS = 'FEATCH_PHONES_SUCCESS'
export const FEATCH_PHONES_FAILURE = 'FEATCH_PHONES_FAILURE'

export const LOAD_MORE_PHONES_START = 'LOAD_MORE_PHONES_START'
export const LOAD_MORE_PHONES_SUCCESS = 'LOAD_MORE_PHONES_SUCCESS'
export const LOAD_MORE_PHONES_FAILURE = 'LOAD_MORE_PHONES_FAILURE'

export const FEATCH_PHONE_BY_ID_START = 'FEATCH_PHONE_BY_ID_START'
export const FEATCH_PHONE_BY_ID_SUCCESS = 'FEATCH_PHONE_BY_ID_SUCCESS'
export const FEATCH_PHONE_BY_ID_FAILURE = 'FEATCH_PHONE_BY_ID_FAILURE'

export const ADD_PHONE_TO_BASKET = 'ADD_PHONE_TO_BASKET'

export const SEARCH_PHONE = 'SEARCH_PHONE'

export const FEATCH_CATEGORIES_START = 'FEATCH_CATEGORIES_START'
export const FEATCH_CATEGORIES_SUCCESS = 'FEATCH_CATEGORIES_SUCCESS'
export const FEATCH_CATEGORIES_FAILURE = 'FEATCH_CATEGORIES_FAILURE'

export const REMOVE_PHONE_FROM_BASKET = 'REMOVE_PHONE_FROM_BASKET'

export const CLEAN_BASKET = 'CLEAN_BASKET'